# Generated by Django 4.1.2 on 2022-11-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_barlist',
            name='urls_field',
            field=models.URLField(default='http://'),
        ),
    ]
