# Generated by Django 4.1.2 on 2022-11-24 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_main_barlist_urls_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_barlist',
            name='urls_field',
        ),
    ]
